name: Publish Package to npm

on:
  push:
    tags:
      - "v*.*.*-.*" # eg v.1.0.0-rc.1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Dep
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish
        run: pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}