name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Dep
        run: pnpm install
      - name: Test
        run: pnpm test
  BuildTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Dep
        run: pnpm install
      - name: Test
        run: pnpm build
  DryPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Dep
        run: pnpm install
      - name: Test
        run: pnpm publish -r --dry-run